name: Meetup FIAP #nome da action
on: [push, pull_request, workflow_dispatch] #quando ela deve ser executada
jobs: # sequencia de passos que serão executadas
  snyk:
    runs-on: ubuntu-latest #maquina que executará a action
    steps:
      - uses: actions/checkout@master #copia o repositório
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master #usa a pasta node no repositório snyk/actions
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }} #obtido no snyk.io
        with:
          command: monitor #envia dados para o snyk ao invés do github actions
  zap:
    runs-on: ubuntu-latest
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: "https://juice-shop.herokuapp.com/" #app OWASP para simular aplicação rodando
          allow_issue_writing: false #desabilitada opção de escrever na guia issues
